# Generated by Django 4.2.15 on 2024-08-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_first_name", models.CharField(max_length=50)),
                ("stu_last_name", models.CharField(max_length=50)),
                ("stu_city", models.CharField(max_length=50)),
                ("stu_email", models.EmailField(max_length=254)),
                ("stu_dob", models.DateField()),
                (
                    "stu_gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("NS", "Not Specified"),
                        ],
                        default="M",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["stu_last_name", "stu_first_name"],
            },
        ),
    ]
