# Generated by Django 4.2.15 on 2024-08-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_order_updated_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="p_name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="p_price",
        ),
    ]
