# Generated by Django 4.2.15 on 2024-08-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_person_pablo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pablo",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
