# Generated by Django 4.2.15 on 2024-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_delete_pablo_delete_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
