# Generated by Django 4.2.15 on 2024-08-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_animal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "animal_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="students.animal",
                    ),
                ),
            ],
            bases=("students.animal",),
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "animal_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="students.animal",
                    ),
                ),
            ],
            bases=("students.animal",),
        ),
    ]
