# Generated by Django 4.2.15 on 2024-08-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_group_person_membership_group_members"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["person", "group"], name="person-group-idx"),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(fields=["-date_joined"], name="date_joined_idx"),
        ),
    ]
