# Generated by Django 4.2.15 on 2024-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial_squashed_0014_jeep_registration"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
                ("occupation", models.CharField(max_length=100)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("join_date", models.DateField()),
            ],
        ),
    ]
