# Generated by Django 4.2.15 on 2024-08-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_dummytable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DummyTable",
        ),
    ]
