# Generated by Django 4.2.15 on 2024-08-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0016_delete_dummytable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=100)),
                ("established_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="DummyTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=100)),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("hire_date", models.DateField()),
                ("is_manager", models.BooleanField(default=False)),
                ("department_name", models.CharField(max_length=100)),
                ("active_status", models.BooleanField(default=True)),
                ("performance_review_date", models.DateField(blank=True, null=True)),
                (
                    "bonus",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.company",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="students.dummytable",
                    ),
                ),
            ],
        ),
    ]
