# Generated by Django 4.2.15 on 2024-08-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0020_remove_comment_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
