# Generated by Django 4.2.15 on 2024-08-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0022_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyPakistan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("num_employees", models.PositiveIntegerField()),
                ("num_chairs", models.PositiveIntegerField()),
            ],
        ),
    ]
