# Generated by Django 4.2.15 on 2024-08-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("students", "0024_com_emp"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                ("phone", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "InstagramUser",
                "verbose_name_plural": "InstagramUsers",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="InstagramReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("H", "Heart"),
                            ("La", "Laugh"),
                            ("S", "Sad"),
                            ("A", "Angry"),
                            ("Li", "Like"),
                        ],
                        max_length=2,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="students.instagramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "InstagramReaction",
                "verbose_name_plural": "InstagramReactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstagramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_caption", models.CharField(max_length=200)),
                ("post_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="students.instagramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "InstagramPost",
                "verbose_name_plural": "InstagramPosts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstagramComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_body", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="students.instagramcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="students.instagrampost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="students.instagramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "InstagramComment",
                "verbose_name_plural": "InstagramComments",
                "ordering": ["created_at"],
            },
        ),
    ]
