# Generated by Django 4.2.15 on 2024-08-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0025_instagramuser_instagramreaction_instagrampost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagrampost",
            name="post_content",
            field=models.CharField(max_length=200),
        ),
    ]
