# Generated by Django 4.2.15 on 2024-08-29 11:04

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0026_alter_instagrampost_post_content"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="instagramcomment",
            managers=[
                ("comment_reactions", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="instagrampost",
            managers=[
                ("post_reactions", django.db.models.manager.Manager()),
            ],
        ),
    ]
